### ISSUE TITLE
Now Playing.widget - Spotify-only (for now) but with cover artwork

### ISSUE THREAD

**Issue by levifig** [felixhageloh/uebersicht-widgets#222]
I saw a bunch of different "Now Playing" widgets but none included both Spotify support and cover artwork so I decided to make my own.

I started from [Patrick's beautiful Last.FM](https://github.com/patrickhpan/lastfm-ubersicht) widget but quickly outgrew it and made my own. I still use quite a bit of Patrick's base design, but expanded it and adapted to my needs (and taste).

Feel free to [check it out](https://github.com/levifig/now-playing.widget), use it, and send some feedback my way! :)

![Screenshot](http://raw.github.com/levifig/now-playing.widget/master/screenshot.png)

**Comment by soberstadt** [comment]
That looks really cool, and some of our contributes might have some feedback on how to improve the code. I tried it out and got an error:
![screenshot 2016-02-04 13 46 44](https://cloud.githubusercontent.com/assets/1080613/12825778/ee605cca-cb45-11e5-90fc-c7fd29e63678.png)

**Comment by levifig** [comment]
@soberstadt That should be fixed! ;) Try re-downloading it… I had a path error! Oops… ;)

**Comment by levifig** [comment]
Ok: solved! I forgot to update the ZIP with some fixes I had included in the code itself… Ooops! :X

Thanks for the feedback! ;)

**Comment by soberstadt** [comment]
I'm still getting the same error, but now the widget is loading. Are you sure there is no way for you to merge this with @patrickhpan's widget?

**Comment by levifig** [comment]
@soberstadt Not really because @patrickhpan's is all about Last.fm… I want to expand this to other players, but not Last.fm. :\

Regarding the error, check the .coffee file and check line 39:
`$.getScript 'now-playing.widget/scripts/jquery.textfill.min.js', ->`

It used to have a typo (`widge` instead of `widget`). Make sure you have the latest (fixed version) version… :) If you do, let me know and I'll investigate (a log from the debug console would be nice ;)).

Thanks.

**Comment by soberstadt** [comment]
I downloaded the updated zip after you said you updated it. And I see widget in that line now. Here is a screenshot of the debug console: ![screenshot 2016-02-04 14 26 34](https://cloud.githubusercontent.com/assets/1080613/12826922/53188a34-cb4b-11e5-8367-a5cf1b562308.png)

@patrickhpan, do you have thoughts on combining them?

**Comment by patrickhpan** [comment]
Hi! @levifig, thanks for the kind words—really appreciate it!

I think that there is definitely a bit of room for more flexibility in terms of the widget, since all songs have titles, artists, albums, and art. However, Spotify, afaik, is a bit different in that you're probably polling a native app while I'm checking a web api. (Correct me if I'm wrong)

I'd be happy to try to help you combine it but since I don't use Spotify, it'll be tough on my end. (I use Google Music)

**Comment by levifig** [comment]
@patrickhpan Credit where credit is due! :) I'd love to add Google Music support as well (eventually), but I haven't looked into their API. And besides, before expanding to other APIs, I'd like to tackle some form of caching.

And @patrickhpan is right: I'm polling the local app for track information and then pulling the metadata via API.

FWIW, I just pushed a bunch of changes (including a new floating layout)… Feedback welcome! ;)

**Comment by patrickhpan** [comment]
I'm not sure how you'd poll Google Play since it has no native desktop app. [https://github.com/radiant-player/radiant-player-mac](https://github.com/radiant-player/radiant-player-mac) does exist and I used to work with that, but Last.FM works for me personally.

I'll take a bit of a look when I'm home—looks interesting!

**Comment by soberstadt** [comment]
Have been having the widget come and go today, giving this error: ![screenshot 2016-02-05 14 41 49](https://cloud.githubusercontent.com/assets/1080613/12857176/b02d5850-cc16-11e5-902c-79857ce326f0.png)

**Comment by levifig** [comment]
@soberstadt I'm getting that error once in a while too. I'm trying to figure out why it happens. Pretty sure it's in the Applescript, probably getting a bad reply from Spotify. Definitely looking into it. Thanks for reporting it.

**Comment by felixhageloh** [comment]
thanks for sharing your widget! I didn't follow the discussion in detail, but is it in a workable state yet (in that case I can add it)?

**Comment by levifig** [comment]
@felixhageloh It's working. I'm seen some of those errors but I'm having a hard time reproducing them. As more people use the widget, I'm sure I'll get more info if it breaks…

Thank you! :)

**Comment by soberstadt** [comment]
@levifig, I am going to try to update what I have on my computer, but at its current state it's annoying. I know that Spotify has had a mixed relationship with Applescript: https://community.spotify.com/t5/Implemented-Ideas/Bring-back-Applescript-support/idc-p/1068934#M31916

**Comment by soberstadt** [comment]
After downloading the latest version of the widget, it still flashes "error running command" in the middle of the song. @felixhageloh, would you be able to help debug this issue? Is it possible to do error handling for this kind of error?

**Comment by felixhageloh** [comment]
I'd have to check in more detail but it is likely that the script prints something to `stderr`. Übersicht will interpret that as an error, but if you don't care to see these errors, you can try to redirect to /dev/null:

```
command: "./my-script.sh  2>/dev/null"
```

In the meantime I have added this widget btw :)
